---
- name: Deploy {{ role }}
  hosts: all
  user: root

  vars :
   - Sojourner_Puppet_Home: /root/Sojourner/Puppet_Manifests
   - puppet_home: /var/tmp/sojourner/puppet
   - manifest: mysql.pp

  pre_tasks:
  - name : Install the puppet
    shell : puppet -V
    ignore_errors: True
    register: puppet_client_installed

  - name: Install the puppet
    yum: name=puppet state=latest
    when: puppet_client_installed|failed

  - name : create puppet_home
    file : path={{ item }}  state=directory recurse=yes
    with_items :
      - "{{ '{{' }} puppet_home {{ '}}' }}"
      - "{{ '{{' }} puppet_home {{ '}}' }}/manifests"
      - "{{ '{{' }} puppet_home {{ '}}' }}/modules"
      - "{{ '{{' }} puppet_home {{ '}}' }}/hieradata"

  - name: Check if module path exists
    stat: path={{ '{{' {{ '}}' }} puppet_home {{ '}}' }}
    register: check_path

  - fail : msg "Can not create module path"
    when : check_path.stat.exists == false

  - name : synchronize puppet modules
    synchronize : src="{{ '{{' {{ '}}' }} Sojourner_Puppet_Home {{ '}}' }}/modules"   dest="{{ '{{' {{ '}}' }} puppet_home {{ '}}' }}" recursive=yes

  - name : Check if manifest path exists
    stat : path="{{ '{{' {{ '}}' }} puppet_home {{ '}}' }}/manifests"
    register: check_path

  - fail : msg "Did not find the manifest path."
    when : check_path.stat.exists == false

  - name : copy manifest
    copy: src="{{ '{{' {{ '}}' }} Sojourner_Puppet_Home {{ '}}' }}/manifests/{{ '{{' {{ '}}' }} manifest {{ '}}' }}" dest="{{ '{{' {{ '}}' }} puppet_home {{ '}}' }}/manifests/"

  tasks:
  - name : Run manifest
    puppet: manifest="{{ '{{' {{ '}}' }} puppet_home {{ '}}' }}/manifests/{{ '{{' {{ '}}' }} manifest {{ '}}' }}" modulepath="{{ '{{' {{ '}}' }} puppet_home {{ '}}' }}/modules"

